add viewmodel for TodoNotesActivity
SegoretPracticum/ToDo pull request #10
Opened 2023-01-12 20:35 UTC by SegoretPracticum

2023-01-13 13:38 UTC, ShmnK1ng commented
вью не оповещает вьюмодель об изменениях состояния (нажатие на кнопку и элемент списка), вьюмодель должна решать что делать вью

2023-01-13 14:18 UTC, SegoretPracticum commented
Ок, буду исправлять

пт, 13 янв. 2023 г., 4:38 PM Andrei Shoka ***@***.***>:

> вью не оповещает вьюмодель об изменениях состояния (нажатие на кнопку и
> элемент списка), вьюмодель должна решать что делать вью
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SegoretPracticum/ToDo/pull/10#issuecomment-1381861288>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2TOGNUDRLYMC2HJFR2NDA3WSFLEVANCNFSM6AAAAAATZVJ3W4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-17 08:24 UTC, onreg requested changes

2023-01-17 08:24 UTC, onreg commented on app/src/main/java/com/example/myapplication/TodoNotesViewModel.java
> +    public void onClickResultProcessing(TodoNotes todoNotes) {
onClickResultProcessing не информативное название.

Я вообще сначало подумал что ты тут клики обрабатываешь, а оказываетсчя результат второго активити.

2023-01-17 08:24 UTC, onreg commented on app/src/main/java/com/example/myapplication/TodoNotesViewModel.java
> +    public MutableLiveData<ArrayList<TodoNotes>> getTodoList() {
Возвращай LiveData<List<TodoNotes>>, чем вью меньше знает тем лучше

2023-01-17 08:24 UTC, onreg commented on app/src/main/java/com/example/myapplication/TodoNotesActivity.java
> +            todoNotesList = todoList;
todoNotesList зачем тебе этот список в активити?

2023-02-01 09:40 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NotesAdapter.java
> +    public List<TodoNotes> notesMassive = new ArrayList<>();
зачем public?

2023-02-01 09:40 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/TodoNotesActivity.java
> +    RecyclerView notesView;
Поставь модефикатор доступа

2023-02-01 09:40 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/TodoNotesActivity.java
>      ActivityResultLauncher<Intent> noteResult = registerForActivityResult(new ActivityResultContracts.StartActivityForResult(), result -> {
Поставь модефикатор доступа

2023-02-01 09:40 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/TodoNotesActivity.java
> +            viewModel.clickReset();
Правильнее будет ресетать состояние в методе onChanged обсервера

2023-02-01 13:24 UTC, onreg requested changes

2023-02-01 13:24 UTC, onreg commented on app/src/main/java/com/example/myapplication/TodoNotesActivity.java
> +    public TodoNotesViewModel viewModel;
проверь модификаторы и добавь пробел хотя бы между viewModel и registerForActivityResult

2023-02-01 13:24 UTC, onreg commented on app/src/main/java/com/example/myapplication/TodoNotesActivity.java
> +            viewModel.clickReset();
тоже самое

2023-02-02 08:14 UTC, onreg requested changes

2023-02-02 08:14 UTC, onreg commented on app/src/main/java/com/example/myapplication/TodoNotesViewModel.java
> +    public void onEventReceived(TodoNotes todoNotes) {
Почему ивент, если тудушка в параметрах?

2023-02-02 16:27 UTC, merged