Mvvm second activity
SegoretPracticum/ToDo pull request #12
Opened 2023-02-09 19:40 UTC by SegoretPracticum

2023-02-10 09:13 UTC, ShmnK1ng approved these changes

2023-02-10 09:13 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +        if (onNavigation) {
тут тоже можно не проверять, окно закроется и все же)

2023-02-10 09:13 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +
в методах с пустым телом, лучше оставить комментарий // do nothing, чтобы было понятно что оно пустое не по ошибке

2023-02-10 09:13 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NoteEditViewModel.java
> +    public LiveData<Boolean> getBackToMainActivityEvent() {
лучше название методов не привязывать к конкретному чему-то, т.к. если ситуация изменится и возвращаться уже будет не в мейн активити, то придется еще и менять название метода

2023-02-10 09:13 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NoteEditViewModel.java
> +    public void emptyInput() {
зачем одну строчку в отдельный метод вынес? тем более что он используется единожды. И модификатор доступа в таком случае private

2023-02-10 11:49 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NoteEditViewModel.java
> +            emptyInput();
по заданию, проверку на пустой текст нужно и выводить ошибку нужно при попытке сохранить тудушку

2023-02-14 09:58 UTC, ShmnK1ng commented on app/src/main/java/com/example/myapplication/NoteEditViewModel.java
>          if (textNote.length() == 0) {
тут такая проверка не нужна, у тебя по факту текст сетается в текстэдит только когда textNote.length() == 0

2023-02-14 10:31 UTC, onreg requested changes

2023-02-14 10:31 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +        enterNote.addTextChangedListener(new TextWatcher() {
Сделай отдельную переменную для TextWatcher, догда сможешь избавится от вложенности

2023-02-14 10:31 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +    private void showToast(Boolean emptyString) {
обрати внимание на имя параметра

2023-02-14 10:31 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +        viewModel.setNewTodo(getIntent().getParcelableExtra(TODO_NOTE));
setNewTodo это можно конструктором заменить

2023-02-14 10:31 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +    private void toolbarItemClicked() {
toolbarItemClicked имя говорит что по тулбару кликнули, а по факту происходит инициализация слушателя. onMenuItemClickListener тоже можешь вынести в переменую.

2023-02-14 15:00 UTC, onreg requested changes

2023-02-14 15:00 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +        todoNotes.setNoteText(enterNote.getText().toString());
Лишняя строка

2023-02-20 13:36 UTC, onreg approved these changes

2023-02-20 15:35 UTC, merged