add toolbars, add button and navigationbutton in the toolbar, change …
SegoretPracticum/ToDo pull request #8
Opened 2022-12-01 22:47 UTC by SegoretPracticum

…image btn in TodoNotesActivity

2022-12-02 15:27 UTC, onreg requested changes

2022-12-02 15:27 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +    public boolean onCreateOptionsMenu(Menu menu) {
onCreateOptionsMenu убрать

2022-12-02 15:27 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +    public boolean onOptionsItemSelected(@NonNull MenuItem item) {
onOptionsItemSelected убрать

2022-12-02 15:27 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +        setSupportActionBar(toolbar);
setSupportActionBar убрать

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content"
android:layout_width="match_parent"

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        tools:layout_editor_absoluteY="1dp" />
tools:layout_editor_absoluteX="1dp"
tools:layout_editor_absoluteY="1dp"

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        style="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
style="@style/ThemeOverlay.AppCompat.Dark.ActionBar"

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        android:theme="?attr/actionBarTheme"
android:theme="?attr/actionBarTheme"

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        android:minHeight="?attr/actionBarSize"
android:minHeight="?attr/actionBarSize"

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        android:background="?attr/colorPrimary"
Для цветов тоже создавай переменные осмысленные как и для текста

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +        android:backgroundTint="#F5A04B"
В ресурсы

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.floatingactionbutton.FloatingActionButton
На кнопке нужно убрать, зелёную границу

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_second.xml
> +    <EditText
Сделай поле ввода на весь экран и убери линию.

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_second.xml
> +        style="@android:style/Widget.EditText"
style="@android:style/Widget.EditText"

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_second.xml
> +        android:layout_marginEnd="@dimen/note_edit_activity_edit_text_margin_end"
слева отступ 24, справа 18 странно

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/layout/activity_second.xml
> +        tools:layout_editor_absoluteY="1dp" />
Тут тоже самое что и с тулбаром на ктивити 1

2022-12-02 15:27 UTC, onreg commented on app/src/main/res/values/strings.xml
> +    <string name="todo_notes_activity_btn_content_description">TODO</string>
Что за TODO?

2022-12-09 11:42 UTC, onreg requested changes

2022-12-09 11:42 UTC, onreg commented on app/src/main/java/com/example/myapplication/NoteEditActivity.java
> +            toolbar.setTitle("Add todo");
"Edit todo", "Add todo" почему не в ресурсах?

2022-12-14 14:39 UTC, SegoretPracticum commented
Merge from toolbar to master

2022-12-14 14:53 UTC, merged